/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyChip {
    'data': {};
    'isDeletable': boolean;
  }
  interface MyCombobox {
    'clearSelection': () => Promise<void>;
    'defaultOptions': any[];
    'isDisabled': boolean;
    'isMultiple': boolean;
    'isOrdered': boolean;
    'label': string;
    'placeholder': string;
  }
  interface MyFormControl {
    'id': string;
    'label': string;
  }
}

declare global {


  interface HTMLMyChipElement extends Components.MyChip, HTMLStencilElement {}
  var HTMLMyChipElement: {
    prototype: HTMLMyChipElement;
    new (): HTMLMyChipElement;
  };

  interface HTMLMyComboboxElement extends Components.MyCombobox, HTMLStencilElement {}
  var HTMLMyComboboxElement: {
    prototype: HTMLMyComboboxElement;
    new (): HTMLMyComboboxElement;
  };

  interface HTMLMyFormControlElement extends Components.MyFormControl, HTMLStencilElement {}
  var HTMLMyFormControlElement: {
    prototype: HTMLMyFormControlElement;
    new (): HTMLMyFormControlElement;
  };
  interface HTMLElementTagNameMap {
    'my-chip': HTMLMyChipElement;
    'my-combobox': HTMLMyComboboxElement;
    'my-form-control': HTMLMyFormControlElement;
  }
}

declare namespace LocalJSX {
  interface MyChip {
    'data'?: {};
    'isDeletable'?: boolean;
    'onMy-chip-delete'?: (event: CustomEvent<any>) => void;
  }
  interface MyCombobox {
    'defaultOptions'?: any[];
    'isDisabled'?: boolean;
    'isMultiple'?: boolean;
    'isOrdered'?: boolean;
    'label'?: string;
    'onMy-change'?: (event: CustomEvent<any>) => void;
    'placeholder'?: string;
  }
  interface MyFormControl {
    'id'?: string;
    'label'?: string;
    'onMy-label-click'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'my-chip': MyChip;
    'my-combobox': MyCombobox;
    'my-form-control': MyFormControl;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-chip': LocalJSX.MyChip & JSXBase.HTMLAttributes<HTMLMyChipElement>;
      'my-combobox': LocalJSX.MyCombobox & JSXBase.HTMLAttributes<HTMLMyComboboxElement>;
      'my-form-control': LocalJSX.MyFormControl & JSXBase.HTMLAttributes<HTMLMyFormControlElement>;
    }
  }
}


