/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyChip {
    'data': {};
    'isDeletable': boolean;
  }
  interface MyCombobox {
    'defaultOptions': any[];
    'isClearable': boolean;
    'isDisabled': boolean;
    'isMultiple': boolean;
    'isOrdered': boolean;
    'isRequired': boolean;
    'label': string;
    'placeholder': string;
  }
  interface MyTextarea {}
}

declare global {


  interface HTMLMyChipElement extends Components.MyChip, HTMLStencilElement {}
  var HTMLMyChipElement: {
    prototype: HTMLMyChipElement;
    new (): HTMLMyChipElement;
  };

  interface HTMLMyComboboxElement extends Components.MyCombobox, HTMLStencilElement {}
  var HTMLMyComboboxElement: {
    prototype: HTMLMyComboboxElement;
    new (): HTMLMyComboboxElement;
  };

  interface HTMLMyTextareaElement extends Components.MyTextarea, HTMLStencilElement {}
  var HTMLMyTextareaElement: {
    prototype: HTMLMyTextareaElement;
    new (): HTMLMyTextareaElement;
  };
  interface HTMLElementTagNameMap {
    'my-chip': HTMLMyChipElement;
    'my-combobox': HTMLMyComboboxElement;
    'my-textarea': HTMLMyTextareaElement;
  }
}

declare namespace LocalJSX {
  interface MyChip {
    'data'?: {};
    'isDeletable'?: boolean;
    'onMy-chip-delete'?: (event: CustomEvent<any>) => void;
  }
  interface MyCombobox {
    'defaultOptions'?: any[];
    'isClearable'?: boolean;
    'isDisabled'?: boolean;
    'isMultiple'?: boolean;
    'isOrdered'?: boolean;
    'isRequired'?: boolean;
    'label'?: string;
    'onMy-change'?: (event: CustomEvent<any>) => void;
    'placeholder'?: string;
  }
  interface MyTextarea {}

  interface IntrinsicElements {
    'my-chip': MyChip;
    'my-combobox': MyCombobox;
    'my-textarea': MyTextarea;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-chip': LocalJSX.MyChip & JSXBase.HTMLAttributes<HTMLMyChipElement>;
      'my-combobox': LocalJSX.MyCombobox & JSXBase.HTMLAttributes<HTMLMyComboboxElement>;
      'my-textarea': LocalJSX.MyTextarea & JSXBase.HTMLAttributes<HTMLMyTextareaElement>;
    }
  }
}


